name: Version Workflow

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Select the version type'
                required: true
                type: choice
                default: 'patch'
                options:
                    - major
                    - minor
                    - patch
                    - dev

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
            
            - run: pip install -r dev-requirements.txt
            
            - name: Bump Version
              run: bump-my-version bump ${{ github.event.inputs.version }}
            - uses: stefanzweifel/git-auto-commit-action@v5
